#! /bin/sh
# /etc/init.d/sysklogd: start the system log daemon.
#
# chkconfig: 2345 10 90
#

#PATH=/bin:/usr/bin:/sbin:/usr/sbin

pidfile=/var/run/syslogd.pid
binpath=/sbin/syslogd

#test -x $binpath || exit 0

# Options for start/restart the daemons
#   For remote UDP logging use SYSLOGD="-r"
#
#SYSLOGD=""
#  Panasonic original: for ROM 2005/10/03
SYSLOGD="-p /var/dev-log"
SYSLOGD_DEBUG="-p /var/dev-log -f /var/log/syslog.conf"

running()
{
    # No pidfile, probably no daemon present
    #
    if [ ! -f $pidfile ]
    then
	return 1
    fi

    pid=`cat $pidfile`

    # No pid, probably no daemon present
    #
    if [ -z "$pid" ]
    then
	return 1
    fi

    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -1`

    # No syslogd?
    #
    if [ "$cmd" != "$binpath" ]
    then
	return 1
    fi

    return 0
}

case "$1" in
  start)
#    echo -n "Starting system log daemon: syslogd"
    start-stop-daemon --start --quiet --exec $binpath -- $SYSLOGD
#    echo "."
    ;;
  start-debug)
    mkfifo /var/log/logfifo
    cp /etc/syslog.conf /var/log/
    echo "*.*  |/var/log/logfifo" > /var/log/syslog.conf
    echo -n "Starting system log daemon: syslogd(fifo[/var/log/logfifo] support)"
    start-stop-daemon --start --quiet --exec $binpath -- $SYSLOGD_DEBUG
    echo "."
    ;;
  stop)
    echo -n "Stopping system log daemon: syslogd"
    start-stop-daemon --stop --quiet --exec $binpath --pidfile $pidfile
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec $binpath --pidfile $pidfile
    ;;
  restart)
    echo -n "Stopping system log daemon: syslogd"
    start-stop-daemon --stop --quiet --exec $binpath --pidfile $pidfile
    echo "."
    sleep 1
    echo -n "Starting system log daemon: syslogd"
    start-stop-daemon --start --quiet --exec $binpath -- $SYSLOGD
    echo "."
    ;;
  restart-debug)
    echo -n "Stopping system log daemon: syslogd"
    start-stop-daemon --stop --quiet --exec $binpath --pidfile $pidfile
    echo "."
    sleep 1
    mkfifo /var/log/logfifo
    cp /etc/syslog.conf /var/log/
    echo "*.*  |/var/log/logfifo" > /var/log/syslog.conf
    echo -n "Starting system log daemon: syslogd(fifo[/var/log/logfifo] support)"
    start-stop-daemon --start --quiet --exec $binpath -- $SYSLOGD_DEBUG
    echo "."
    ;;
  reload-or-restart)
    if running
    then
	start-stop-daemon --stop --quiet --signal 1 --exec $binpath --pidfile $pidfile
    else
	start-stop-daemon --start --quiet --exec $binpath -- $SYSLOGD
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/sysklogd {start|stop|reload|restart|force-reload|reload-or-restart}"
    exit 1
esac

exit 0
