#! /bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	See if system needs to be setup. This is ONLY meant to
#	be used for the initial setup after a fresh installation!
#
#if [ -x /sbin/unconfigured.sh ]
#then
#  /sbin/unconfigured.sh
#fi

#
#	Source defaults.
#
. /etc/default/rcS
export VERBOSE

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
#for i in /etc/rc.d/rcS.d/S??*
#do
	# Ignore dangling symlinks for now.
#	[ ! -f "$i" ] && continue

#	case "$i" in
#		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set start
#				. $i
				. /etc/rc.d/rcS.d/S10rcSd.sh
			)
#			;;
#		*)
			# No sh extension, so fork subprocess.
#			$i start
#			;;
#	esac
#done
#	Run /etc/rc.d/rc.local if it exists
#         modified by Panasonic
#
#[ -x /etc/rc.d/rc.local ] && /etc/rc.d/rc.local

#
#	Finish setup if needed. The comment above about
#	/sbin/unconfigured.sh applies here as well!
#
#        modified by Panasonic
#
#if [ -x /sbin/setup.sh ]
#then
#  /sbin/setup.sh
#fi

